[theme]
base = "dark"
primaryColor = "#57e2e5"                     # Aurelius blue accent
backgroundColor = "#121212"                  # Carbon dark background
secondaryBackgroundColor = "#1f1f1f"         # Slight contrast
textColor = "#f1f1f1"                        # Soft white
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[ui]
hideTopBar = true

